### ISSUE TITLE
[QST] The example of continous wavelet transformation (CWT) does not work on my laptop

### ISSUE THREAD

**Issue by shevateng0** [rapidsai/cusignal#424]
I would like to try the example of CWT with ricker wavelet, but some error is reported. The code is listed below which is exactly the same as in https://docs.rapids.ai/api/cusignal/stable/api.html#wavelets.
```
import cusignal
import cupy as cp
import matplotlib.pyplot as plt
t = cp.linspace(-1, 1, 200, endpoint=False)
sig  = cp.cos(2 * cp.pi * 7 * t) + cusignal.gausspulse(t - 0.4, fc=2)
widths = cp.arange(1, 31)
cwtmatr = cusignal.cwt(sig, cusignal.ricker, widths)
plt.imshow(cp.asnumpy(cwtmatr), extent=[-1, 1, 31, 1], cmap='PRGn',
               aspect='auto', vmax=abs(cwtmatr).max(),
               vmin=-abs(cwtmatr).max())
plt.show()
```
The reported error is listed below. 
```
Traceback (most recent call last):
  File "cupytest.py", line 19, in <module>
    cwtmatr = cusignal.cwt(sig, cusignal.ricker, widths)
  File "/home/xinux/miniconda3/lib/python3.8/site-packages/cusignal/wavelets/wavelets.py", line 310, in cwt
    wavelet_data = wavelet(min(10 * width, len(data)), width)
  File "/home/xinux/miniconda3/lib/python3.8/site-packages/cusignal/wavelets/wavelets.py", line 175, in ricker
    return _ricker_kernel(a, size=points)
  File "cupy/_core/_kernel.pyx", line 784, in cupy._core._kernel.ElementwiseKernel.__call__
TypeError: 'cupy._core.core.ndarray' object cannot be interpreted as an integer
```
Since no error appeared when I tried the example of spectrogram, I believe the installation of cuda, cupy and cusignal is successful. Please kindly help me resolve this issue. Thanks.

Some info are listed below in case you need.
- My laptop is HP Pavilion gaming laptop with graphics card GTX1650.
- Use Python3.8 and cuda11.2.
- Both cupy and cusignal are installed via conda. The commands are listed below:
```
conda install -c rapidsai -c nvidia -c conda-forge \
    cusignal=21.08 python=3.8 cudatoolkit=11.2 
conda install -c conda-forge cupy
```

**Comment by awthomp** [comment]
Hi @shevateng0 -- I've confirmed this is a valid bug (I get the same error on my local machine), and we'll prioritize getting it fixed! Thanks for using cusignal and submitting the issue.
